/**
 * BabyJubJub curve helpers.
 *
 * Noble-curves exports `babyjubjub` from `@noble/curves/misc`.  Its curve
 * order `n = 8*l` includes the cofactor, so point arithmetic works correctly.
 *
 * For Schnorr / FROST we operate in the prime-order subgroup generated by
 * BASE8 (= 8·G, the circomlib generator).  All scalars are reduced mod
 * ORDER = l.  This makes our TypeScript code byte-compatible with
 * schnorr_verify.circom which hard-codes the same BASE8 point.
 */

import { babyjubjub as _bjj } from "@noble/curves/misc";

// Prime-order subgroup generator — matches circomlib BASE8 (EIP-2494).
const BASE8_AFFINE = {
  x: 5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  y: 16950150798460657717958625567821834550301663161624707787222815936182638968203n,
};

/** Prime subgroup order l = babyjubjub.n / 8 (from EIP-2494). */
export const ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

export type Point = { x: bigint; y: bigint };

function pointFromExtended(
  p: ReturnType<typeof _bjj.ExtendedPoint.fromAffine>
): Point {
  const aff = p.toAffine();
  return { x: aff.x, y: aff.y };
}

/** Multiply the BASE8 generator by `scalar` (scalar in [0, ORDER)). */
export function scalarMulBase(scalar: bigint): Point {
  return pointFromExtended(
    _bjj.ExtendedPoint.fromAffine(BASE8_AFFINE).multiply(scalar)
  );
}

/** Multiply an arbitrary curve point by `scalar`. */
export function scalarMul(scalar: bigint, point: Point): Point {
  return pointFromExtended(
    _bjj.ExtendedPoint.fromAffine(point).multiply(scalar)
  );
}

/** Add two curve points. */
export function pointAdd(a: Point, b: Point): Point {
  return pointFromExtended(
    _bjj.ExtendedPoint.fromAffine(a).add(_bjj.ExtendedPoint.fromAffine(b))
  );
}

/** Reduce `a` into [0, m). */
export function mod(a: bigint, m: bigint = ORDER): bigint {
  return ((a % m) + m) % m;
}
